// GENERATED by scripts/registry-plugins/api.mjs — do not edit.
// Type-safe client for the REAL Radio Vaigyaaniq endpoints (registry api metadata).
// Planned /api/v1 aliases are intentionally absent until they exist.

export interface SdkOptions {
  /** radio-backend origin, e.g. "http://localhost:4000". */
  baseUrl: string;
  fetchImpl?: typeof fetch;
}

export interface EntitlementDto { scope: string; trackId: string | null; albumId: string | null; active: boolean }
export interface WalletDto { currency: "INR" | "USD"; balance: number }
export interface PaymentOrderRequest {
  userId: string;
  productType: "track" | "album" | "all_access";
  trackId?: string;
  albumId?: string;
  currency?: "INR" | "USD";
}
export interface PaymentOrderResponse { orderId: string; amount: number; currency: "INR" | "USD"; purchaseId: string; keyId: string }
export interface SyncEvent { type: string; payload: Record<string, unknown>; queuedAt?: string }

export function createRadioSdk(options: SdkOptions) {
  const call = async <T>(method: "GET" | "POST", pathName: string, body?: unknown): Promise<T> => {
    const doFetch = options.fetchImpl ?? fetch;
    const response = await doFetch(`${options.baseUrl}${pathName}`, {
      method,
      headers: { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body)
    });
    if (!response.ok) throw new Error(`${method} ${pathName} → ${response.status}`);
    return (await response.json()) as T;
  };
  return {
    getStations: () => call<unknown[]>("GET", "/api/stations"),
    getSchedule: (stationSlug: string) => call<unknown[]>("GET", `/api/schedule/${encodeURIComponent(stationSlug)}`),
    getEvidence: () => call<Record<string, unknown>>("GET", "/api/evidence"),
    getOfflineBundle: (userId?: string) =>
      call<Record<string, unknown>>("GET", `/api/offline-bundle${userId ? `?userId=${encodeURIComponent(userId)}` : ""}`),
    getEntitlements: (userId: string) =>
      call<{ status: string; entitlements: EntitlementDto[]; wallets: WalletDto[] }>(
        "GET",
        `/api/entitlements/${encodeURIComponent(userId)}`
      ),
    getStreamCandidates: () => call<Record<string, unknown>>("GET", "/api/stream-candidates"),
    getWeather: (city?: string) =>
      call<Record<string, unknown>>("GET", `/api/weather${city ? `?city=${encodeURIComponent(city)}` : ""}`),
    createPaymentOrder: (request: PaymentOrderRequest) =>
      call<PaymentOrderResponse>("POST", "/api/payments/order", request),
    syncOutbox: (userId: string, events: SyncEvent[]) =>
      call<{ status: string; accepted: number }>("POST", "/api/sync", { userId, events }),
    getSearch: (query: string) => call<Record<string, unknown>>("GET", `/api/search?q=${encodeURIComponent(query)}`),
    getAnalytics: () => call<Record<string, unknown>>("GET", "/api/analytics")
  };
}

export type RadioSdk = ReturnType<typeof createRadioSdk>;
