import type { PrismaClient } from "@prisma/client";

export async function getObservatoryMetrics(prisma: PrismaClient) {
  const [
    nodeCount,
    edgeCount,
    lineageCount,
    civilizationCount,
    subjectCount,
    citationCount,
    verificationGroups,
    pitraCount,
    guruMaataaCount,
    rishiCount,
    rishikaCount,
    textCount,
    languageCount,
    timelineEventCount,
    locationCount,
    institutionCount,
    discoveryCount,
    innovationCount,
    mediaAssetCount,
    researchPaperCount,
    courseCount,
    relationshipCount,
    auditLogCount,
    sanskritLexemeCount
  ] = await Promise.all([
    prisma.knowledgeNode.count(),
    prisma.knowledgeEdge.count(),
    prisma.lineage.count(),
    prisma.civilization.count(),
    prisma.subject.count(),
    prisma.auditLog.count({ where: { action: "cited" } }),
    prisma.knowledgeNode.groupBy({ by: ["verificationStatus"], _count: true }),
    prisma.pitra.count(),
    prisma.guruMaataa.count(),
    prisma.rishi.count(),
    prisma.rishika.count(),
    prisma.text.count(),
    prisma.language.count(),
    prisma.timelineEvent.count(),
    prisma.location.count(),
    prisma.institution.count(),
    prisma.discovery.count(),
    prisma.innovation.count(),
    prisma.mediaAsset.count(),
    prisma.researchPaper.count(),
    prisma.course.count(),
    prisma.relationship.count(),
    prisma.auditLog.count(),
    prisma.sanskritLexeme.count()
  ]);

  return {
    nodeCount,
    edgeCount,
    lineageCount,
    civilizationCount,
    subjectCount,
    citationCount,
    textCount,
    sanskritLexemeCount,
    auditLogCount,
    relationshipCount,
    verificationStatus: Object.fromEntries(verificationGroups.map((row) => [row.verificationStatus, row._count])),
    persistenceCounts: {
      pitra: pitraCount,
      guruMaataa: guruMaataaCount,
      rishi: rishiCount,
      rishika: rishikaCount,
      civilization: civilizationCount,
      subject: subjectCount,
      language: languageCount,
      text: textCount,
      sanskritLexeme: sanskritLexemeCount,
      knowledgeNode: nodeCount,
      knowledgeEdge: edgeCount,
      institution: institutionCount,
      timelineEvent: timelineEventCount,
      location: locationCount,
      discovery: discoveryCount,
      innovation: innovationCount,
      mediaAsset: mediaAssetCount,
      researchPaper: researchPaperCount,
      course: courseCount,
      lineage: lineageCount,
      relationship: relationshipCount,
      auditLog: auditLogCount
    }
  };
}
