// Route-registry helpers for the catch-all renderer.
// The registry (lib/route-registry.json, generated by scripts/build-route-registry.mjs)
// is the single source of truth for the ecosystem IA and its honest statuses.
import registry from "./route-registry.json";

export type RouteStatus = "built" | "partial" | "planned";

export interface RegistryRoute {
  path: string;
  section: string;
  emoji: string;
  title: string;
  status: RouteStatus;
  implementedBy: string[];
  description: string;
  dynamic: boolean;
}

export interface RouteMatch {
  route: RegistryRoute;
  params: Record<string, string>;
}

const routes = registry.routes as RegistryRoute[];

// Precomputed O(1) lookups (schemaVersion 2 registries carry stable ids).
// Additive: the original matchRoute/childrenOf/bySection API is unchanged.
type EnrichedRoute = RegistryRoute & { id?: string; layout?: string };
const byExactPath = new Map<string, RegistryRoute>(routes.map((route) => [route.path, route]));
const byRouteId = new Map<string, RegistryRoute>(
  (routes as EnrichedRoute[]).filter((route) => route.id).map((route) => [route.id as string, route])
);
const dynamicOnly = routes.filter((route) => route.dynamic);

/** O(1) lookup by permanent route id (e.g. "radio.live"). Never use URL strings internally. */
export function getRouteById(id: string): RegistryRoute | undefined {
  return byRouteId.get(id);
}

export const routeRegistry = registry as {
  generatedAt: string;
  phkd: { failClosed: boolean; note: string };
  counts: Record<string, number>;
  sections: Array<{ name: string; emoji: string }>;
  routes: RegistryRoute[];
};

/** Match a pathname against the registry (exact O(1) first, then :param patterns). */
export function matchRoute(pathname: string): RouteMatch | null {
  const clean = `/${pathname.split("/").filter(Boolean).join("/")}`;
  const exact = byExactPath.get(clean);
  if (exact) return { route: exact, params: {} };

  const parts = clean.split("/").filter(Boolean);
  for (const route of dynamicOnly) {
    const patternParts = route.path.split("/").filter(Boolean);
    if (patternParts.length !== parts.length) continue;
    const params: Record<string, string> = {};
    let ok = true;
    for (let index = 0; index < patternParts.length; index += 1) {
      const pattern = patternParts[index];
      if (pattern.startsWith(":")) params[pattern.slice(1)] = decodeURIComponent(parts[index]);
      else if (pattern !== parts[index]) {
        ok = false;
        break;
      }
    }
    if (ok) return { route, params };
  }
  return null;
}

/** Direct children of a hub path (one segment deeper), for hub listings. */
export function childrenOf(pathname: string): RegistryRoute[] {
  const base = pathname === "/" ? "" : pathname;
  const depth = base.split("/").filter(Boolean).length + 1;
  return routes.filter(
    (route) =>
      route.path !== pathname &&
      route.path.startsWith(`${base}/`) &&
      route.path.split("/").filter(Boolean).length === depth
  );
}

/** All routes grouped by section, for the ecosystem overview. */
export function bySection(): Map<string, RegistryRoute[]> {
  const map = new Map<string, RegistryRoute[]>();
  for (const route of routes) {
    if (!map.has(route.section)) map.set(route.section, []);
    map.get(route.section)!.push(route);
  }
  return map;
}
