// api plugin: api-map.json (UI ↔ API), openapi.json (real endpoints; planned
// aliases listed under x-planned), and a generated type-safe client SDK
// (apps/radio/lib/sdk.ts — real endpoints only, no fabricated methods).
export async function generate(ctx) {
  const { registry, generatedAt, SITE_ORIGIN } = ctx;
  const { allRoutes } = registry;

  const apiMap = { generatedAt, byRoute: {}, byEndpoint: {} };
  for (const route of allRoutes) {
    if (!route.api.length) continue;
    apiMap.byRoute[route.id] = route.api;
    for (const ref of route.api) {
      const key = `${ref.method} ${ref.path}`;
      apiMap.byEndpoint[key] = apiMap.byEndpoint[key] || { status: ref.status, description: ref.description || null, usedBy: [] };
      apiMap.byEndpoint[key].usedBy.push(route.id);
    }
  }
  ctx.artifacts.apiMap = apiMap;

  // ---- OpenAPI 3.1 (honest: only existing endpoints become paths) ----
  const paths = {};
  const planned = [];
  for (const [key, meta] of Object.entries(apiMap.byEndpoint)) {
    const [method, endpointPath] = key.split(" ");
    if (meta.status === "planned") {
      planned.push({ method, path: endpointPath, description: meta.description });
      continue;
    }
    const openapiPath = endpointPath.replace(/:([A-Za-z]+)/g, "{$1}");
    paths[openapiPath] = paths[openapiPath] || {};
    paths[openapiPath][method.toLowerCase()] = {
      summary: meta.description || key,
      tags: [meta.usedBy[0]?.split(".")[0] || "radio"],
      "x-used-by-routes": meta.usedBy,
      parameters: [...openapiPath.matchAll(/\{([A-Za-z]+)\}/g)].map((match) => ({
        name: match[1],
        in: "path",
        required: true,
        schema: { type: "string" }
      })),
      responses: { "200": { description: "OK" }, "4XX": { description: "Fail-closed (PHKD) or validation error" } }
    };
  }
  const openapi = {
    openapi: "3.1.0",
    info: {
      title: "Radio Vaigyaaniq API",
      version: "1.0.0",
      description:
        "Generated from the route registry. Only endpoints that exist are documented as paths; versioned /api/v1 aliases are planned (see x-planned)."
    },
    servers: [{ url: SITE_ORIGIN }, { url: "http://localhost:4000", description: "radio-backend" }],
    paths,
    "x-planned": planned,
    "x-generated-at": generatedAt
  };

  // ---- typed client SDK (real endpoints only) ----
  const sdk = `// GENERATED by scripts/registry-plugins/api.mjs — do not edit.
// Type-safe client for the REAL Radio Vaigyaaniq endpoints (registry api metadata).
// Planned /api/v1 aliases are intentionally absent until they exist.

export interface SdkOptions {
  /** radio-backend origin, e.g. "http://localhost:4000". */
  baseUrl: string;
  fetchImpl?: typeof fetch;
}

export interface EntitlementDto { scope: string; trackId: string | null; albumId: string | null; active: boolean }
export interface WalletDto { currency: "INR" | "USD"; balance: number }
export interface PaymentOrderRequest {
  userId: string;
  productType: "track" | "album" | "all_access";
  trackId?: string;
  albumId?: string;
  currency?: "INR" | "USD";
}
export interface PaymentOrderResponse { orderId: string; amount: number; currency: "INR" | "USD"; purchaseId: string; keyId: string }
export interface SyncEvent { type: string; payload: Record<string, unknown>; queuedAt?: string }

export function createRadioSdk(options: SdkOptions) {
  const call = async <T>(method: "GET" | "POST", pathName: string, body?: unknown): Promise<T> => {
    const doFetch = options.fetchImpl ?? fetch;
    const response = await doFetch(\`\${options.baseUrl}\${pathName}\`, {
      method,
      headers: { "content-type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body)
    });
    if (!response.ok) throw new Error(\`\${method} \${pathName} → \${response.status}\`);
    return (await response.json()) as T;
  };
  return {
    getStations: () => call<unknown[]>("GET", "/api/stations"),
    getSchedule: (stationSlug: string) => call<unknown[]>("GET", \`/api/schedule/\${encodeURIComponent(stationSlug)}\`),
    getEvidence: () => call<Record<string, unknown>>("GET", "/api/evidence"),
    getOfflineBundle: (userId?: string) =>
      call<Record<string, unknown>>("GET", \`/api/offline-bundle\${userId ? \`?userId=\${encodeURIComponent(userId)}\` : ""}\`),
    getEntitlements: (userId: string) =>
      call<{ status: string; entitlements: EntitlementDto[]; wallets: WalletDto[] }>(
        "GET",
        \`/api/entitlements/\${encodeURIComponent(userId)}\`
      ),
    getStreamCandidates: () => call<Record<string, unknown>>("GET", "/api/stream-candidates"),
    getWeather: (city?: string) =>
      call<Record<string, unknown>>("GET", \`/api/weather\${city ? \`?city=\${encodeURIComponent(city)}\` : ""}\`),
    createPaymentOrder: (request: PaymentOrderRequest) =>
      call<PaymentOrderResponse>("POST", "/api/payments/order", request),
    syncOutbox: (userId: string, events: SyncEvent[]) =>
      call<{ status: string; accepted: number }>("POST", "/api/sync", { userId, events }),
    getSearch: (query: string) => call<Record<string, unknown>>("GET", \`/api/search?q=\${encodeURIComponent(query)}\`),
    getAnalytics: () => call<Record<string, unknown>>("GET", "/api/analytics")
  };
}

export type RadioSdk = ReturnType<typeof createRadioSdk>;
`;

  return [
    ["apps/radio/public/registry/api-map.json", `${JSON.stringify(apiMap, null, 2)}\n`],
    ["apps/radio/public/registry/openapi.json", `${JSON.stringify(openapi, null, 2)}\n`],
    ["apps/radio/lib/sdk.ts", sdk],
    // Phase 5: the same generated client ships as the workspace SDK package.
    ["packages/sdk-client/src/index.ts", sdk],
    ["packages/sdk-client/openapi.json", `${JSON.stringify(openapi, null, 2)}\n`]
  ];
}
